/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BillDAL;
import Controller.GuestDAL;
import Controller.RoomsDAL;
import Controller.UserDAL;
import Model.Bill;
import Model.Guest;
import Model.Room;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author NT_Thanh
 */
public class BillPanel extends javax.swing.JPanel{
    private Guest guest;
    private Room room;
    private Bill bill;
    private float money;
    private BillDAL us;
    private RoomsDAL rs;
    private UserDAL ur;
    private int index, id_user;
    private Date t, date,dt_af,dt_dk;
    private String date_begin, date_af, iuser;
    
    private ArrayList<Integer> listRoom;
    /**
     * Creates new form BillPanel
     */
    // set param for bill panel
    public BillPanel(String username) {
        initComponents();
        jdcDate_end.setDate(new Date());
        SetCombobox();
        iuser = username;
   
    }
    public void SetCombobox()
    {
        RoomsDAL us = new RoomsDAL();
        listRoom = us.GetRoomAllNotEmpty();
        for(int s : listRoom){   
            cbPhong.addItem(String.valueOf(s));
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPhong = new javax.swing.JComboBox<>();
        jdcDate_end = new com.toedter.calendar.JDateChooser();
        txtdate_begin = new javax.swing.JTextField();
        txtngdaidien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        year = new com.toedter.calendar.JYearChooser();
        month = new com.toedter.calendar.JMonthChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCSDO = new javax.swing.JTextField();
        txtCSDN = new javax.swing.JTextField();
        txtCSNO = new javax.swing.JTextField();
        txtCSNN = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtphuchi = new javax.swing.JTextField();
        btnthanhtoan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnxuathoadon = new javax.swing.JButton();
        txttongtien = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        validation_csd = new javax.swing.JLabel();
        validation_csn = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btntraphong = new javax.swing.JButton();
        lbdien = new javax.swing.JLabel();
        lbnuoc = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        cbPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPhongActionPerformed(evt);
            }
        });

        jdcDate_end.setBackground(new java.awt.Color(255, 255, 255));
        jdcDate_end.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtdate_begin.setEditable(false);
        txtdate_begin.setBackground(new java.awt.Color(255, 255, 255));
        txtdate_begin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdate_begin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtngdaidien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtngdaidien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtngdaidien.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Phòng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Người Đại Diện");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ngày Trước");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ngày Sau");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tháng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Năm");

        year.setBackground(new java.awt.Color(255, 255, 255));
        year.setStartYear(2020);

        month.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        month.setPreferredSize(new java.awt.Dimension(200, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Chỉ Số Điện Mới");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Chỉ Số Điện Cũ");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Chỉ Số Nước Cũ");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Chỉ Số Nước Mới");

        txtCSDO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCSDO.setEnabled(false);

        txtCSDN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCSNO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCSNO.setEnabled(false);

        txtCSNN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("Phụ Chi");

        txtphuchi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtphuchi.setForeground(new java.awt.Color(255, 153, 0));
        txtphuchi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtphuchi.setText("0");

        btnthanhtoan.setBackground(new java.awt.Color(102, 0, 102));
        btnthanhtoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnthanhtoan.setForeground(new java.awt.Color(255, 255, 255));
        btnthanhtoan.setText("Thanh Toán");
        btnthanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhtoanActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Tiền Trọ");

        btnxuathoadon.setBackground(new java.awt.Color(102, 0, 102));
        btnxuathoadon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnxuathoadon.setForeground(new java.awt.Color(255, 255, 255));
        btnxuathoadon.setText("Xuất Hóa Đơn");
        btnxuathoadon.setEnabled(false);
        btnxuathoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuathoadonActionPerformed(evt);
            }
        });

        txttongtien.setBackground(new java.awt.Color(255, 255, 255));
        txttongtien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttongtien.setForeground(new java.awt.Color(255, 0, 0));
        txttongtien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txttongtien.setText("0");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("THÔNG TIN  HÓA ĐƠN");

        validation_csd.setBackground(new java.awt.Color(255, 255, 255));
        validation_csd.setForeground(new java.awt.Color(255, 0, 0));

        validation_csn.setBackground(new java.awt.Color(255, 255, 255));
        validation_csn.setForeground(new java.awt.Color(255, 0, 0));

        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("____________________________________________________________________________________________________");

        btntraphong.setBackground(new java.awt.Color(102, 0, 102));
        btntraphong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntraphong.setForeground(new java.awt.Color(255, 255, 255));
        btntraphong.setText("Thanh Lý ");
        btntraphong.setEnabled(false);
        btntraphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntraphongActionPerformed(evt);
            }
        });

        lbdien.setForeground(new java.awt.Color(255, 204, 153));

        lbnuoc.setForeground(new java.awt.Color(255, 204, 153));

        txtprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Giá Phòng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtngdaidien)
                        .addComponent(txtdate_begin)
                        .addComponent(jdcDate_end, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(cbPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(year, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCSNO, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtCSDN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(validation_csd, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(lbnuoc))))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbdien)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprice)
                            .addComponent(txtCSDO)
                            .addComponent(txtphuchi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCSNN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validation_csn, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btntraphong, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(btnxuathoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(72, 72, 72)
                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtprice)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtngdaidien, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbdien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdate_begin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCSDN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCSDO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(validation_csd, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcDate_end, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCSNO, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(validation_csn, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbnuoc)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCSNN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtphuchi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntraphong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxuathoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPhongActionPerformed
        // TODO add your handling code here:
        String item = cbPhong.getSelectedItem().toString();
        index = Integer.parseInt(item);
        //get index combobox
        ur = new UserDAL();
        id_user = ur.FindUser(iuser);
        //get id users
        
        //get guest
        GuestDAL gs = new GuestDAL();
        guest = gs.GetByIDPhong(index);
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        
        
        
        String date_dk = guest.getNgaydk();
        try {
            dt_dk = sdf.parse(date_dk);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
        //get room
        rs = new RoomsDAL();
        room = rs.GetRoomByID(index);
        txtprice.setText(String.valueOf(room.getPrice()));
        //get bill
        us = new BillDAL();
        bill = us.GetDateEndLast(room.getTen());
        if(us.FindBillExsistFirst(room.getTen())!=0)
        {
           date_af = bill.getDate_end();
                try {
                    dt_af = sdf.parse(date_af);
                } catch (ParseException ex) {
                    Logger.getLogger(BillPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        else
        {
            
        }
        
        if(guest!=null)
        {
            
            if(us.FindBillExsistFirst(room.getTen())==0||dt_dk.getTime()>=dt_af.getTime())
            {
                String date = sdf.format(dt_dk);
                txtdate_begin.setText(date);
                txtngdaidien.setText(guest.getName()); 
            }
            else
            {
                
                //String date = sdf.format(date_af);
                txtdate_begin.setText(date_af);
                txtngdaidien.setText(guest.getName());
            }
            txtCSDO.setText(String.valueOf(room.getChisodien_old()));
            txtCSNO.setText(String.valueOf(room.getChisonuoc_old()));
            
        }
        
    }//GEN-LAST:event_cbPhongActionPerformed

    private void btnthanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhtoanActionPerformed
        // TODO add your handling code here:
        if(txtCSDN.getText().equals(""))
            {
                validation_csd.setText("*");
            }
            if(txtCSNN.getText().equals("")){
                validation_csn.setText("*");
            }
            if(!txtCSDN.getText().equals(""))
            {
                validation_csd.setText("");
            }
            if(!txtCSNN.getText().equals("")){
                validation_csn.setText("");
            }
            if(!(txtCSDN.getText().equals("")||txtCSNN.getText().equals("")))
            {
                money=0;
                SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
                
                //ngay dau thang hien tai
                LocalDate currentdate = LocalDate.now();
                int currentYear = currentdate.getYear();
                Date ll = new Date();
                int currentMonth = ll.getMonth()+1;
                String date_chotstr=null;
                if(currentMonth<10)
                {
                    date_chotstr = currentYear+"-"+"0"+currentMonth+"-01";
                } 
                else
                {
                    date_chotstr = currentYear+"-"+currentMonth+"-01";
                }
                //yyyy-dd-mm
                Date date_chot=null;
                try {
                    date_chot = sdf.parse(date_chotstr);
                } catch (ParseException ex) {
                    Logger.getLogger(BillPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                //ngay dau thang hien tai
                
                //ngay hien tai
                int currentDay = currentdate.getDayOfMonth();
                String date_nowstr=null;
                if(currentMonth<10)
                {
                    date_nowstr = currentYear+"-"+"0"+currentMonth+"-"+currentDay;
                }
                if(currentDay<10)
                {
                    date_nowstr = currentYear+"-"+currentMonth+"-"+"0"+currentDay;
                }
                if(currentMonth<10&&currentDay<10)
                {
                    date_nowstr = currentYear+"-"+"0"+currentMonth+"-"+"0"+currentDay;
                }
                Date date_now_chot=null;
                try {
                    date_now_chot = sdf.parse(date_nowstr);
                } catch (ParseException ex) {
                    Logger.getLogger(BillPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                //ngay hien tai
                
                
                
                
                
                validation_csd.setText("");
                validation_csn.setText("");
                btntraphong.setEnabled(true);
                btnxuathoadon.setEnabled(true); 
                
                
                date = jdcDate_end.getDate();
                date_begin = txtdate_begin.getText();
                try {
                    t = sdf.parse(date_begin);
                } catch (ParseException ex) {
                    Logger.getLogger(BillPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
                //get days with monthnow =month+1
                
                LocalDate date_1 = LocalDate.parse(date_begin);
                LocalDate date_chot_dauthang = LocalDate.parse(date_chotstr);
                LocalDate date_now = LocalDate.parse(date_nowstr);
                
             

                //neu monthnow> monthdk 1
                int diffInDays;
                JOptionPane.showMessageDialog(this, date_nowstr);
                //Begin cal money
                if(date_1.getDayOfMonth()!=1&&date_chot_dauthang.getMonthValue()-date_1.getMonthValue()==1)
                {
                    diffInDays = (int)( (date_chot.getTime()-t.getTime()) / (1000 * 60 * 60 * 24));
                    money += Float.parseFloat(txtprice.getText().toString())*diffInDays/30;
                }
                else if(date_1.getDayOfMonth()==1&&date_chot_dauthang.getMonthValue()-date_1.getMonthValue()==1)
                {
                         money+=Float.parseFloat(txtprice.getText().toString());
                   
                }
                else if(date_1.getDayOfMonth()==1&&date_now.getMonthValue()==date_1.getMonthValue())
                {
                    diffInDays = (int)( (date_now_chot.getTime()-t.getTime()) / (1000 * 60 * 60 * 24));
                    money += Float.parseFloat(txtprice.getText().toString())*diffInDays/30;
                }
                int moneycsd = Integer.parseInt(txtCSDN.getText())- Integer.parseInt(txtCSDO.getText());
                int moneycsn = Integer.parseInt(txtCSNN.getText())- Integer.parseInt(txtCSNO.getText());

                money += moneycsd*3000+moneycsn*11000;
                int phuchi = Integer.parseInt(txtphuchi.getText())!=0 ? Integer.parseInt(txtphuchi.getText()): 0;
                money += phuchi;
                //End cal money

                txttongtien.setText(String.valueOf(money));
            }
    }//GEN-LAST:event_btnthanhtoanActionPerformed

    private void btnxuathoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuathoadonActionPerformed
        // TODO add your handling code here:
        if(txtCSDN.getText().equals("")|| txtCSNN.getText().equals(""))          
           {
               JOptionPane.showMessageDialog(this, "Please into infor!");
               btntraphong.setEnabled(false);
               btnxuathoadon.setEnabled(false); 
           }
           else
           {
               SimpleDateFormat f= new SimpleDateFormat("yyyy-MM-dd");
               int id = index;
               String tenphong = room.getTen();
               String nguoidaidien = txtngdaidien.getText();
               String date_1 = txtdate_begin.getText();
               Date dt_end = jdcDate_end.getDate();
               String date_2 = f.format(dt_end);
               int total_CSD = Integer.parseInt(txtCSDN.getText())-Integer.parseInt(txtCSDO.getText());
               int total_CSN = Integer.parseInt(txtCSNN.getText())-Integer.parseInt(txtCSNO.getText());
               int getmonth = month.getMonth();
               int getyear = year.getYear();
               
               //Insert bill
               if(us.AddBill(id, tenphong, nguoidaidien, date_1, date_2, getmonth+1, getyear, total_CSD, total_CSN, money, iuser))
               {
                   JOptionPane.showMessageDialog(this, "Xuất hóa đơn thành công!");
               }
               
               // Create report
               us.ReportBill(us.GetIDEndLast());
               
               //update csd, csn for room
               rs.UpdateRoomByID(index, txtCSDN.getText(), txtCSNN.getText());
           }
    }//GEN-LAST:event_btnxuathoadonActionPerformed

    private void btntraphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntraphongActionPerformed
        if (JOptionPane.showConfirmDialog(this,
            "Bạn có chắc muốn thanh lý?", "Thông Báo", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            
                GuestDAL us = new GuestDAL();
                int x = Integer.parseInt(cbPhong.getSelectedItem().toString());
                if(us.RemoveRoom(x))
                {
                    JOptionPane.showMessageDialog(this, "Trả phòng thành công!");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Phòng chưa tồn tại!");
                }

        }else
        {
            
        }
       
       
        
        
    }//GEN-LAST:event_btntraphongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthanhtoan;
    private javax.swing.JButton btntraphong;
    private javax.swing.JButton btnxuathoadon;
    private javax.swing.JComboBox<String> cbPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jdcDate_end;
    private javax.swing.JLabel lbdien;
    private javax.swing.JLabel lbnuoc;
    private com.toedter.calendar.JMonthChooser month;
    private javax.swing.JTextField txtCSDN;
    private javax.swing.JTextField txtCSDO;
    private javax.swing.JTextField txtCSNN;
    private javax.swing.JTextField txtCSNO;
    private javax.swing.JTextField txtdate_begin;
    private javax.swing.JTextField txtngdaidien;
    private javax.swing.JTextField txtphuchi;
    private javax.swing.JTextField txtprice;
    private javax.swing.JLabel txttongtien;
    private javax.swing.JLabel validation_csd;
    private javax.swing.JLabel validation_csn;
    private com.toedter.calendar.JYearChooser year;
    // End of variables declaration//GEN-END:variables

    
}
