/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BillDAL;
import Model.Bill;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author NT_Thanh
 */
public class ThongKe extends javax.swing.JPanel {
    private ArrayList<Bill> list;
    DefaultTableModel model;
    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
        setVisible(true);
        LoadData();
    }
    public void LoadData()
    {
        String x = cbmonth.getSelectedItem().toString();
        int item = x.equals("Tháng")?0:Integer.parseInt(x);
        BillDAL us = new BillDAL();
        list = us.GetBillByMonth(item);
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
            
        };
        tbbill.setModel(model);
         model.setColumnIdentifiers(new Object[]{
            "TÊN PHÒNG","NGƯỜI ĐẠI DIỆN" ,"CHỈ SỐ ĐIỆN", "CHỈ SỐ NƯỚC", "NGÀY XUẤT HÓA ĐƠN", "TỔNG TIỀN"
        });
         //set background table
        JTableHeader tableHeader = tbbill.getTableHeader();
        tableHeader.setBackground(new Color(102, 0, 102));
        tableHeader.setForeground(Color.WHITE);
        tableHeader.setPreferredSize(new Dimension(350, 30));
        
        TableColumnModel columnModel = tbbill.getColumnModel();
//           set align center data table
        for(Bill s : list){
            model.addRow(new Object[]{s.getPhong(), s.getNguoidaidien(), 
                                      s.getTotal_csd(), s.getTotal_csn(),s.getDate_end(), 
                                      s.getMoney()}
            );
          DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(JLabel.CENTER);
            columnModel.getColumn(0).setCellRenderer(renderer);
            columnModel.getColumn(1).setCellRenderer(renderer);
            columnModel.getColumn(2).setCellRenderer(renderer);
            columnModel.getColumn(3).setCellRenderer(renderer);
            columnModel.getColumn(4).setCellRenderer(renderer);
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbmonth = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbbill = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        cbmonth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbmonth.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmonthItemStateChanged(evt);
            }
        });
        cbmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmonthActionPerformed(evt);
            }
        });

        tbbill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbbill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbbill.setFillsViewportHeight(true);
        tbbill.setGridColor(new java.awt.Color(204, 204, 204));
        tbbill.setRowHeight(30);
        jScrollPane2.setViewportView(tbbill);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỐNG KÊ HÓA ĐƠN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cbmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbmonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmonthItemStateChanged
        LoadData();
    }//GEN-LAST:event_cbmonthItemStateChanged

    private void cbmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmonthActionPerformed
        LoadData();
    }//GEN-LAST:event_cbmonthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbmonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbbill;
    // End of variables declaration//GEN-END:variables
}
