/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UserDAL;
import Model.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;

/**
 *
 * @author NT_Thanh
 */
public class TrangChu extends javax.swing.JFrame {

    private String isuser = null;
    /**
     * Creates new form TrangChu
     */
    public TrangChu(String username, int permissive) {
        initComponents();
        isuser = username;
        setLocationRelativeTo(null);
        jPanel2.removeAll();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(new Home());
        jPanel2.validate();
        jPanel2.repaint();
        setVisible(true);
        setTitle("QUẢN LÝ NHÀ TRỌ");
        if(permissive == 0)
        {
            jUser.setEnabled(false);
            jUser.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    JOptionPane.showMessageDialog(rootPane, "Bạn không có quyền!");
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    
                }

            });
        }
        else{
            jUser.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    jPanel2.removeAll();
                    jPanel2.setLayout(new BorderLayout());
                    jPanel2.add(new QLNhanVien());
                    jPanel2.validate();
                    jPanel2.repaint();
                    jUser.setForeground(new Color(255, 102, 102));
                    jInfor.setForeground(Color.WHITE);
                    jGuest.setForeground(Color.WHITE);
                    jRoom.setForeground(Color.WHITE);
                    JHoadon.setForeground(Color.WHITE);
                    jthongke.setForeground(Color.WHITE);
                }

                @Override
                public void mousePressed(MouseEvent e) {
                    
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                  
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    
                }
            });
        }
        
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jhome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jInfor = new javax.swing.JLabel();
        jRoom = new javax.swing.JLabel();
        jGuest = new javax.swing.JLabel();
        JHoadon = new javax.swing.JLabel();
        jUser = new javax.swing.JLabel();
        jthongke = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("framTrangChu"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(128, 0, 128));

        jhome.setBackground(new java.awt.Color(255, 153, 0));
        jhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jhomeMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHÀ TRỌ");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/baseline_home_white_18dp.png"))); // NOI18N

        javax.swing.GroupLayout jhomeLayout = new javax.swing.GroupLayout(jhome);
        jhome.setLayout(jhomeLayout);
        jhomeLayout.setHorizontalGroup(
            jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jhomeLayout.createSequentialGroup()
                .addGroup(jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jhomeLayout.setVerticalGroup(
            jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInfor.setBackground(new java.awt.Color(255, 255, 255));
        jInfor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jInfor.setForeground(new java.awt.Color(255, 255, 255));
        jInfor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jInfor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/baseline_done_all_white_18dp.png"))); // NOI18N
        jInfor.setText("Thông Tin Cá Nhân");
        jInfor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInfor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jInfor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInforMouseClicked(evt);
            }
        });

        jRoom.setBackground(new java.awt.Color(255, 255, 255));
        jRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRoom.setForeground(new java.awt.Color(255, 255, 255));
        jRoom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/baseline_done_all_white_18dp.png"))); // NOI18N
        jRoom.setText("Quản Lí Phòng");
        jRoom.setAlignmentY(0.0F);
        jRoom.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRoomMouseClicked(evt);
            }
        });

        jGuest.setBackground(new java.awt.Color(255, 255, 255));
        jGuest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jGuest.setForeground(new java.awt.Color(255, 255, 255));
        jGuest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jGuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/baseline_done_all_white_18dp.png"))); // NOI18N
        jGuest.setText("Quản Lí Khách Thuê");
        jGuest.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGuestMouseClicked(evt);
            }
        });

        JHoadon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JHoadon.setForeground(new java.awt.Color(255, 255, 255));
        JHoadon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/baseline_done_all_white_18dp.png"))); // NOI18N
        JHoadon.setText("Thanh Toán Hóa Đơn");
        JHoadon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        JHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JHoadonMouseClicked(evt);
            }
        });

        jUser.setBackground(new java.awt.Color(255, 255, 255));
        jUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jUser.setForeground(new java.awt.Color(255, 255, 255));
        jUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/baseline_done_all_white_18dp.png"))); // NOI18N
        jUser.setText("Quản Lý Nhân Viên");
        jUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jthongke.setBackground(new java.awt.Color(255, 255, 255));
        jthongke.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jthongke.setForeground(new java.awt.Color(255, 255, 255));
        jthongke.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jthongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/baseline_done_all_white_18dp.png"))); // NOI18N
        jthongke.setText("Thống Kê Hóa Đơn");
        jthongke.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jthongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jthongkeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jhome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInfor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jGuest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JHoadon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jthongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jhome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUser, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jInfor.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jhomeMouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(new Home());
        jPanel2.validate();
        jPanel2.repaint();
        jUser.setForeground(Color.WHITE);
        jInfor.setForeground(Color.WHITE);
        jGuest.setForeground(Color.WHITE);
        jRoom.setForeground(Color.WHITE);
         JHoadon.setForeground(Color.WHITE);
         jthongke.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_jhomeMouseClicked

    
    private void jRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRoomMouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(new RoomPanel());
        jPanel2.validate();
        jPanel2.repaint();
        jRoom.setForeground(new Color(255, 102, 102));
        jInfor.setForeground(Color.WHITE);
        jGuest.setForeground(Color.WHITE);
        jUser.setForeground(Color.WHITE);
         JHoadon.setForeground(Color.WHITE);
         jthongke.setForeground(Color.WHITE);
       
    }//GEN-LAST:event_jRoomMouseClicked

    private void jGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGuestMouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(new GuestPanel());
        jPanel2.validate();
        jPanel2.repaint();
        jGuest.setForeground(new Color(255, 102, 102));
        jInfor.setForeground(Color.WHITE);
        jUser.setForeground(Color.WHITE);
        jRoom.setForeground(Color.WHITE);
        JHoadon.setForeground(Color.WHITE);
        jthongke.setForeground(Color.WHITE);
       
    }//GEN-LAST:event_jGuestMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to close this window?", "Close Window?", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
       
    }//GEN-LAST:event_formWindowClosing

    private void JHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JHoadonMouseClicked
        // TODO add your handling code here:
        jPanel2.removeAll();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(new BillPanel(isuser));
        jPanel2.validate();
        jPanel2.repaint();
        JHoadon.setForeground(new Color(255, 102, 102));
        jGuest.setForeground(Color.WHITE);
        jInfor.setForeground(Color.WHITE);
        jUser.setForeground(Color.WHITE);
        jRoom.setForeground(Color.WHITE);
        jthongke.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_JHoadonMouseClicked

    private void jInforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInforMouseClicked
        // TODO add your handling code here:
        //Binding data textfield
        UserDAL infouser = new UserDAL();
        User s =new User();
        s = infouser.SingleUser(isuser);

        jPanel2.removeAll();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(new InforPanel(s));
        jPanel2.validate();
        jPanel2.repaint();
        jInfor.setForeground(new Color(255, 102, 102));
        jUser.setForeground(Color.WHITE);
        jGuest.setForeground(Color.WHITE);
        jRoom.setForeground(Color.WHITE);
        JHoadon.setForeground(Color.WHITE);
        jthongke.setForeground(Color.WHITE);
        

    }//GEN-LAST:event_jInforMouseClicked

    private void jthongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jthongkeMouseClicked
         jPanel2.removeAll();
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(new ThongKe());
        jPanel2.validate();
        jPanel2.repaint();
        jthongke.setForeground(new Color(255, 102, 102));
        jUser.setForeground(Color.WHITE);
        jGuest.setForeground(Color.WHITE);
        jRoom.setForeground(Color.WHITE);
        JHoadon.setForeground(Color.WHITE);
        jInfor.setForeground(Color.WHITE);
    }//GEN-LAST:event_jthongkeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TrangChu(isuser).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JHoadon;
    private javax.swing.JLabel jGuest;
    private javax.swing.JLabel jInfor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jRoom;
    private javax.swing.JLabel jUser;
    private javax.swing.JPanel jhome;
    private javax.swing.JLabel jthongke;
    // End of variables declaration//GEN-END:variables

    
}
